data <- read.table("~/Lista-vs-ABB/amostra.txt", header=T)
options(scipen=5)
maxY <- max(data$bst)
maxX <- max(data$size)
minX <- min(data$size)
minY <- min(data$bst)
plot(data$bst~data$size, col="red", xlab="Size", ylab="Comparisons", xlim=c(minX, maxX), ylim=c(minY, maxY))
title(main = "ABB")
legend("topleft", c("ABB"), col=c("red"), pch=1, inset = c(0.05, 0.05)) 

